# Generated by Django 2.1.5 on 2019-02-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('data', models.TextField(verbose_name='Data')),
                ('image', models.ImageField(upload_to='meme_images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OGMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(blank=True, max_length=255, verbose_name='Top Text')),
                ('bottom', models.CharField(blank=True, max_length=255, verbose_name='Bottom Text')),
                ('image', models.ImageField(upload_to='ogmeme')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='templates')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='twitmeme')),
                ('text', models.TextField(verbose_name='Text')),
                ('slug', models.SlugField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Template')),
            ],
        ),
        migrations.AddField(
            model_name='ogmeme',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Template'),
        ),
        migrations.AddField(
            model_name='meme',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Template'),
        ),
        migrations.AlterUniqueTogether(
            name='twitmeme',
            unique_together={('text', 'template')},
        ),
        migrations.AlterUniqueTogether(
            name='ogmeme',
            unique_together={('top', 'bottom', 'template')},
        ),
    ]
