# Generated by Django 2.1.5 on 2019-01-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='OGMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=255, verbose_name='Top Text')),
                ('bottom', models.CharField(max_length=255, verbose_name='Bottom Text')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.Template')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ogmeme',
            unique_together={('top', 'bottom', 'template')},
        ),
    ]
