# Generated by Django 2.1.5 on 2019-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20190121_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogmeme',
            name='bottom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bottom Text'),
        ),
        migrations.AlterField(
            model_name='ogmeme',
            name='top',
            field=models.CharField(blank=True, max_length=255, verbose_name='Top Text'),
        ),
    ]
