# Generated by Django 2.1.5 on 2019-01-23 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20190121_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ogmeme',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ogmeme',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
