# Generated by Django 2.1.5 on 2019-01-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20190123_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogmeme',
            name='image',
            field=models.ImageField(default='fake', upload_to='ogmeme'),
            preserve_default=False,
        ),
    ]
