# Generated by Django 2.1.5 on 2019-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0006_ogmeme_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogmeme',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AddField(
            model_name='ogmeme',
            name='slug',
            field=models.SlugField(default='nothing'),
            preserve_default=False,
        ),
    ]
